export {};
function packArr(arr){let s="";const b=new Uint8Array(arr.buffer,arr.byteOffset,arr.byteLength);for(let i=0;i<b.length;i+=8192)s+=String.fromCharCode.apply(null,b.subarray(i,i+8192));return btoa(s)}
function unpackArr(b64,Ctor,len){const bin=atob(b64),bytes=new Uint8Array(len*Ctor.BYTES_PER_ELEMENT);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);return new Ctor(bytes.buffer)}
const entRef=v=>v?{id:v.id,e:v.e}:null;
function unitToObj(u){return{id:u.id,key:u.key,owner:u.owner,x:u.x,y:u.y,hp:u.hp,maxhp:u.maxhp,ang:u.ang,tang:u.tang,order:u.order,tx:u.tx,ty:u.ty,cool:u.cool,cargo:u.cargo,ore:u.ore,unload:u.unload,deployed:u.deployed,xp:u.xp,vet:u.vet,alt:u.alt,ammo:u.ammo,inside:entRef(u.inside),host:entRef(u.host),drone:entRef(u.drone),erase:u.erase,frozen:u.frozen,state:u.state,home:entRef(u.home),origOwner:u.origOwner,slaves:(u.slaves||[]).map(entRef),ctrlBy:entRef(u.ctrlBy),target:entRef(u.target),ref:entRef(u.ref),guard:u.guard,ctrl:u.ctrl,rangeMul:u.rangeMul,slowT:u.slowT,retreatT:u.retreatT,revealT:u.revealT}}
function bldToObj(b){return{id:b.id,key:b.key,owner:b.owner,tx:b.tx,ty:b.ty,size:b.size,hp:b.hp,maxhp:b.maxhp,cool:b.cool,target:entRef(b.target),rally:b.rally,sellT:b.sellT,repair:b.repair,chargeT:b.chargeT,charge:b.charge,rise:b.rise,spin:b.spin,capturedFac:b.capturedFac,garrison:(b.garrison||[]).map(entRef),deployed:b.deployed,rot:b.rot,open:b.open,pairId:entRef(b.pairId?{id:b.pairId,e:"b"}:null)}}
function restoreUnit(rec){const d=UNITS[rec.key];if(!d)return null;return{id:rec.id,e:"u",key:rec.key,d,owner:rec.owner,x:rec.x,y:rec.y,hp:rec.hp,maxhp:rec.maxhp,ang:rec.ang||0,tang:rec.tang||0,order:rec.order||"idle",tx:rec.tx,ty:rec.ty,path:null,pi:0,repath:0,target:null,cool:rec.cool||0,cargo:rec.cargo||0,ore:rec.ore||null,ref:null,unload:rec.unload||0,dead:!1,vx:0,vy:0,moving:!1,stuck:0,ctrl:rec.ctrl||0,ctrlBy:null,origOwner:null!=rec.origOwner?rec.origOwner:rec.owner,slaves:[],recoil:0,muzzle:0,deployed:rec.deployed,guard:rec.guard,xp:rec.xp||0,vet:rec.vet||0,alt:rec.alt||0,ammo:rec.ammo||0,inside:null,host:null,drone:null,erase:rec.erase||0,frozen:rec.frozen||0,state:rec.state||null,home:null,rangeMul:rec.rangeMul,slowT:rec.slowT,retreatT:rec.retreatT,revealT:rec.revealT,_refTarget:rec.target,_refRef:rec.ref,_refCtrlBy:rec.ctrlBy,_refInside:rec.inside,_refHost:rec.host,_refDrone:rec.drone,_refHome:rec.home,_refSlaves:rec.slaves||[]}}
function restoreBld(rec){const bd=BLD[rec.key];if(!bd)return null;const owner=S.players[rec.owner],fac=owner?owner.fac:"allied",sz=rec.size||bd.size;return{id:rec.id,e:"b",key:rec.key,d:bd,owner:rec.owner,tx:rec.tx,ty:rec.ty,size:sz,x:32*(rec.tx+sz/2),y:32*(rec.ty+sz/2),hp:rec.hp,maxhp:rec.maxhp,name:bname(rec.key,fac),cool:rec.cool||0,target:null,dead:!1,rally:rec.rally||null,sellT:rec.sellT||0,repair:!!rec.repair,chargeT:rec.chargeT||0,charge:rec.charge||0,rise:null!=rec.rise?rec.rise:1,w:bweapon(rec.key,fac),w2:bd.weapon2||null,spin:rec.spin||0,capturedFac:rec.capturedFac||null,deployed:rec.deployed,rot:rec.rot||0,open:!!rec.open,gateT:rec.open?1:0,garrison:[],_refTarget:rec.target,_refGarrison:rec.garrison||[],_refPairId:rec.pairId}}
function resolveRefs(){const findE=(r:any):any=>{if(!r)return null;const list="u"===r.e?S.units:S.blds;return list.find(o=>o.id===r.id)||null};for(const u of S.units){u.target=findE(u._refTarget),u.ref=findE(u._refRef),u.ctrlBy=findE(u._refCtrlBy),u.inside=findE(u._refInside),u.host=findE(u._refHost),u.drone=findE(u._refDrone),u.home=findE(u._refHome),u.slaves=((u._refSlaves as any[])||[]).map(findE).filter(Boolean);delete u._refTarget,delete u._refRef,delete u._refCtrlBy,delete u._refInside,delete u._refHost,delete u._refDrone,delete u._refHome,delete u._refSlaves}for(const b of S.blds){b.target=findE(b._refTarget),b.garrison=((b._refGarrison as any[])||[]).map(findE).filter(Boolean);const pairE=findE(b._refPairId);b.pairId=pairE?pairE.id:null;delete b._refTarget,delete b._refGarrison,delete b._refPairId}}
function playerToObj(p){return{id:p.id,fac:p.fac,isAI:p.isAI,diff:p.diff,team:p.team,color:p.color,dark:p.dark,tint:p.tint,neutral:p.neutral,credits:p.credits,power:p.power,drain:p.drain,queues:p.queues,ready:p.ready,kills:p.kills,lost:p.lost,defeated:p.defeated,spawnX:p.spawnX,spawnY:p.spawnY,spyCD:p.spyCD,paradropCD:p.paradropCD,empCD:p.empCD,ai:p.isAI?{t:p.ai.t,wave:p.ai.wave,expand:p.ai.expand}:null}}
function restorePlayer(rec){if(rec.neutral){const np=newPlayer(rec.id,"allied",!1,"normal",rec.team,null);return np.f={key:"neutral",name:"Civilian",color:"#9c968a",dark:"#6a6252",tint:"#ccc",units:[],miner:"miner_allied",base:"gi",main:"grizzly",anti:"gi",elite:"gi"},np.fac="neutral",np.neutral=!0,np.credits=rec.credits||0,np}const p=newPlayer(rec.id,rec.fac,rec.isAI,rec.diff,rec.team,{body:rec.color,dark:rec.dark,tint:rec.tint});return p.credits=rec.credits,p.power=rec.power,p.drain=rec.drain,p.queues=rec.queues||{bld:null,inf:null,veh:null,air:null},p.ready=rec.ready||{bld:null},p.kills=rec.kills||0,p.lost=rec.lost||0,p.defeated=!!rec.defeated,p.spawnX=rec.spawnX,p.spawnY=rec.spawnY,p.spyCD=rec.spyCD||0,p.paradropCD=rec.paradropCD||0,p.empCD=rec.empCD||0,p.isAI&&rec.ai&&(p.ai.t=rec.ai.t,p.ai.wave=rec.ai.wave||0,p.ai.expand=rec.ai.expand||0),p}
function serializeMap(){return{map:G.map,seed:G.seed,terr:packArr(G.terr),ore:packArr(G.ore),tib:packArr(G.tib),blk:packArr(G.blk),pave:packArr(G.pave),vis:packArr(G.vis),elev:packArr(G.elev),mtn:packArr(G.mtn),tint:packArr(G.tint),civ:G.civ,special:G.special,props:G.props,oreSpots:G.oreSpots,fall:G.fall,spots:G.spots}}
function restoreMap(rec){G.map=rec.map,G.seed=rec.seed,G.terr=unpackArr(rec.terr,Uint8Array,6624),G.ore=unpackArr(rec.ore,Float32Array,6624),G.tib=unpackArr(rec.tib,Uint8Array,6624),G.blk=unpackArr(rec.blk,Uint8Array,6624),G.pave=unpackArr(rec.pave,Uint8Array,6624),G.vis=unpackArr(rec.vis,Uint8Array,6624),G.elev=unpackArr(rec.elev,Float32Array,6624),G.mtn=unpackArr(rec.mtn,Float32Array,6624),G.tint=unpackArr(rec.tint,Uint8Array,6624),G.occ=new Int32Array(6624),G.civ=rec.civ||[],G.special=rec.special||[],G.props=rec.props||[],G.oreSpots=rec.oreSpots||[],G.fall=rec.fall||[],G.spots=rec.spots||[],G.trees=[]}
function serializeGame(){return{v:1,time:S.time,fogOn:FOG_ON,neutral:NEUTRAL,cfg:JSON.parse(JSON.stringify(cfg)),cam:{x:cam.x,y:cam.y,z:cam.z},nextId:S.nextId,mission:S.mission,players:S.players.map(playerToObj),units:S.units.filter(u=>!u.dead).map(unitToObj),blds:S.blds.filter(b=>!b.dead).map(bldToObj),rads:(S.rads||[]).map(r=>({x:r.x,y:r.y,r:r.r,life:r.life,owner:r.owner})),weather:S.weather,map:serializeMap()}}
function restoreGame(data){cfg=data.cfg||cfg;restoreMap(data.map);NEUTRAL=data.neutral;S.players=data.players.map(restorePlayer);S.units=data.units.map(restoreUnit).filter(Boolean);S.blds=data.blds.map(restoreBld).filter(Boolean);S.bldById=new Map(S.blds.map(b=>[b.id,b]));resolveRefs();for(const b of S.blds)if(!("gate"===b.key&&b.open))for(let ty=b.ty;ty<b.ty+b.size;ty++)for(let tx=b.tx;tx<b.tx+b.size;tx++)inMap(tx,ty)&&(G.occ[idx(tx,ty)]=b.id);for(const p of S.players)recalcPower(p.id);S.time=data.time,S.weather=data.weather||"clear",setRainAmbience("rain"===S.weather),S.over=!1,S.running=!0,S.sel=[],S.projs=[],S.fx=[],S.rockets=[],S.traffic=[],S.rads=(data.rads||[]).map(r=>({x:r.x,y:r.y,r:r.r,life:r.life,owner:r.owner})),S.aiVis=new Map,S.knownEnemy=new Map,S.nextId=data.nextId||Math.max(1,...S.units.map(u=>u.id),...S.blds.map(b=>b.id))+1,S.mission=data.mission||null,FOG_ON=data.fogOn,cam.x=data.cam.x,cam.y=data.cam.y,cam.z=camZTarget=data.cam.z,mmCache=null,GL?rebuildTerrainGL():initGL(),resizeGL(),"function"==typeof onFogUpdated&&onFogUpdated(),"function"==typeof setFogUniform&&setFogUniform(FOG_ON),$("#top").classList.remove("hidden"),$("#side").classList.remove("hidden"),$("#mmWrap").classList.remove("hidden"),buildCards(),S.running=!0,openMenu(null),hint("Game loaded")}
function loadSlot(n){try{const s=localStorage.getItem("ifr_save"+n);if(!s)return void hint("Slot empty");restoreGame(JSON.parse(s))}catch(e){hint("Load failed")}}
function saveMeta(n){try{const s=localStorage.getItem("ifr_save"+n);if(!s)return null;const d=JSON.parse(s);return{fac:d.cfg.fac,map:d.cfg.map,time:d.time,mission:d.mission?CAMPAIGNS[d.mission.fac].missions[d.mission.idx].name:null}}catch(e){return null}}
Object.assign(window, {
  serializeGame, loadSlot, saveMeta
});
